runtime: php72

#entrypoint: serve install.php

#automatic_scaling:
#  target_cpu_utilization: 0.65
#  min_instances: 0
#  max_instances: 1
#  min_pending_latency: 30ms  # default value
#  max_pending_latency: automatic
#  max_concurrent_requests: 50

handlers:
- url: /(.*\.(htm|html|css|js|ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
  static_files: \1
  upload: .*\.(htm|html|css|js|ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
- url: /.*
  script: auto
  secure: always
#  redirect_http_response_code: 301